In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql
SELECT *
  FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [11]:
%%sql
SELECT
  EXTRACT(YEAR FROM orderdate) AS year,
  SUM(netprice) AS total_yearly_net_income
FROM sales
GROUP BY
  year
ORDER BY
  year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   year  total_yearly_net_income
0  2015               2411195.64
1  2016               3379301.20
2  2017               4229458.39
3  2018               7950000.89
4  2019               9972332.59
5  2020               3593779.50
6  2021               6742864.28
7  2022              13907299.92
8  2023              10069875.60
9  2024               2561994.76

In [13]:
%%sql

SELECT *
FROM information_schema.tables
WHERE table_schema = 'public' ;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,contoso_100k,public,currencyexchange,BASE TABLE,None,None,None,None,None,YES,NO,None
1,contoso_100k,public,customer,BASE TABLE,None,None,None,None,None,YES,NO,None
2,contoso_100k,public,sales,BASE TABLE,None,None,None,None,None,YES,NO,None
3,contoso_100k,public,date,BASE TABLE,None,None,None,None,None,YES,NO,None
4,contoso_100k,public,product,BASE TABLE,None,None,None,None,None,YES,NO,None
5,contoso_100k,public,store,BASE TABLE,None,None,None,None,None,YES,NO,None

In [14]:
%%sql
SELECT *
FROM currencyexchange
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82

In [16]:
%%sql
SELECT *
FROM date
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2

In [17]:
%%sql
SELECT *
FROM store
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None

In [19]:
%%sql
SELECT *
FROM information_schema.columns

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2046 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,pg_catalog,pg_attribute,attinhcount,21,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,pg_catalog,pg_stat_gssapi,pid,1,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2,contoso_100k,pg_catalog,pg_stat_gssapi,gss_authenticated,2,None,YES,boolean,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
3,contoso_100k,pg_catalog,pg_attribute,attcollation,22,None,NO,oid,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,pg_catalog,pg_stat_gssapi,encrypted,4,None,YES,boolean,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2041,contoso_100k,pg_catalog,pg_type,typdefault,31,None,YES,text,NaN,1073741824.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2042,contoso_100k,pg_catalog,pg_statistic_ext,stxname,3,None,NO,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2043,contoso_100k,pg_catalog,pg_statio_user_tables,relname,3,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2044,contoso_100k,pg_catalog,pg_statio_user_tables,schemaname,2,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2045,contoso_100k,pg_catalog,pg_statio_sys_tables,relname,3,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO

In [22]:
# selecting a specific table
%%sql
SELECT *
FROM information_schema.columns
WHERE table_name = 'date'
ORDER BY ordinal_position

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

17 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,date,date,1,None,NO,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,date,datekey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,date,year,3,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,date,yearquarter,4,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,date,yearquarternumber,5,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,date,quarter,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,date,yearmonth,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,date,yearmonthshort,8,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,date,yearmonthnumber,9,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,date,month,10,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,date,monthshort,11,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,date,monthnumber,12,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,date,dayofweek,13,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,date,dayofweekshort,14,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,date,dayofweeknumber,15,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,date,workingday,16,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,date,workingdaynumber,17,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [26]:
# selecting specific columns from specific table
%%sql
SELECT
storecode,
state,
opendate
FROM store
ORDER BY storecode desc

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

74 rows affected.

    storecode                         state    opendate
0          67                       Wyoming  2014-01-01
1          66                 West Virginia  2012-01-01
2          65                 Washington DC  2010-01-01
3          63                          Utah  2008-03-06
4          62                  South Dakota  2018-06-03
..        ...                           ...         ...
69          3               South Australia  2012-01-07
70          3               South Australia  2015-12-08
71          2            Northern Territory  2008-01-12
72          1  Australian Capital Territory  2008-01-01
73         -1                        Online  2010-01-01

[74 rows x 3 columns]

In [29]:
%%sql
SELECT *
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [33]:
# Running some operations on 'sales' table
# getting the net revenue by some multiplication
%%sql

SELECT orderdate,
  quantity*netprice*exchangerate AS net_revenue
FROM sales
ORDER BY orderdate desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2024-04-20       588.00
1  2024-04-20      2201.80
2  2024-04-20       103.25
3  2024-04-20       204.61
4  2024-04-20      1276.20
5  2024-04-20     27247.76
6  2024-04-20        14.02
7  2024-04-20       269.22
8  2024-04-20        80.83
9  2024-04-20       569.05

In [36]:
# looking for data available after 1 jan 2024

%%sql

SELECT orderdate,
  quantity*netprice*exchangerate AS net_revenue
FROM sales
WHERE orderdate >= '2024-01-01'
ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10131 rows affected.

        orderdate  net_revenue
0      2024-01-01         6.28
1      2024-01-01        82.56
2      2024-01-01       307.26
3      2024-01-01       777.00
4      2024-01-01        98.52
...           ...          ...
10126  2024-04-20       914.61
10127  2024-04-20       150.18
10128  2024-04-20       147.78
10129  2024-04-20      2019.62
10130  2024-04-20        56.83

[10131 rows x 2 columns]

In [39]:
%%sql
SELECT *
FROM customer
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14

In [46]:
# joining the tables
%%sql

SELECT s.orderdate,
  s.quantity*s.netprice*s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE orderdate >= '2024-01-01'
ORDER BY s.orderdate desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue givenname   surname    countryfull      continent
0  2024-04-20       113.86      Leah  Docherty  United States  North America
1  2024-04-20        56.83   Michael    Wilson         Canada  North America
2  2024-04-20      2019.62   Michael    Wilson         Canada  North America
3  2024-04-20       147.78   Michael    Wilson         Canada  North America
4  2024-04-20       150.18  Karlotta   Rivière         France         Europe
5  2024-04-20       914.61  Karlotta   Rivière         France         Europe
6  2024-04-20       187.02  Karlotta   Rivière         France         Europe
7  2024-04-20      3909.87  Virginie     Patel         France         Europe
8  2024-04-20       664.15  Virginie     Patel         France         Europe
9  2024-04-20        38.94  Virginie     Patel         France         Europe

In [47]:
%%sql
SELECT *
FROM product
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3

In [53]:
# moving forward we want to join one more table to get the product information
%%sql

SELECT s.orderdate,
  s.quantity*s.netprice*s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productname,
  p.categoryname,
  p.subcategoryname
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE orderdate >= '2024-01-01'
ORDER BY s.orderdate desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productname,categoryname,subcategoryname
0,2024-04-20,113.86,Leah,Docherty,United States,North America,Contoso Phone Tough Skin Case E140 White,Cell phones,Cell phones Accessories
1,2024-04-20,56.83,Michael,Wilson,Canada,North America,SV Hand Games men M30 Black,Games and Toys,Boxed Games
2,2024-04-20,2019.62,Michael,Wilson,Canada,North America,Proseware Laptop8.9 E089 White,Computers,Laptops
3,2024-04-20,147.78,Michael,Wilson,Canada,North America,SV DVD Player M140 Gold,"Music, Movies and Audio Books",Movie DVD
4,2024-04-20,150.18,Karlotta,Rivière,France,Europe,Contoso DVD 9-Inch Player Portable M300 Black,"Music, Movies and Audio Books",Movie DVD
5,2024-04-20,914.61,Karlotta,Rivière,France,Europe,Contoso DVD 9-Inch Player Portable M300 Silver,"Music, Movies and Audio Books",Movie DVD
6,2024-04-20,187.02,Karlotta,Rivière,France,Europe,The Phone Company Microsoft Windows Mobile M20...,Cell phones,Smart phones & PDAs
7,2024-04-20,3909.87,Virginie,Patel,France,Europe,Fabrikam Independent Filmmaker 1/3'' 8.5mm X20...,Cameras and camcorders,Camcorders
8,2024-04-20,664.15,Virginie,Patel,France,Europe,A. Datum Interchangeable lens Non-SLR Digital ...,Cameras and camcorders,Digital Cameras
9,2024-04-20,38.94,Virginie,Patel,France,Europe,MGS Hand Games men M300 Silver,Games and Toys,Boxed Games

In [61]:
# adding a condition to include 'High' and 'Low' for net_revenue
%%sql

SELECT s.orderdate,
  s.quantity*s.netprice*s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productname,
  p.categoryname,
  p.subcategoryname,
CASE WHEN   s.quantity*s.netprice*s.exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS status
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE orderdate >= '2024-01-01'
ORDER BY s.orderdate desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productname,categoryname,subcategoryname,status
0,2024-04-20,461.35,Ashley,Jordan,Australia,Australia,MGS Zoo Tycoon 2 E108,Games and Toys,Download Games,LOW
1,2024-04-20,2352.38,Ferragus,Fresne,France,Europe,"Contoso SLR Camera 35"" M358 Grey",Cameras and camcorders,Digital SLR Cameras,HIGH
2,2024-04-20,971.64,Vera,Velasco,United States,North America,Litware Home Theater System 2.1 Channel E211 B...,TV and Video,Home Theater System,LOW
3,2024-04-20,278.39,Scott,Youmans,United States,North America,SV DVD 15-Inch Player Portable L200 Black,"Music, Movies and Audio Books",Movie DVD,LOW
4,2024-04-20,316.56,Nate,Hyland,Australia,Australia,Contoso DVD Player M100 Black,"Music, Movies and Audio Books",Movie DVD,LOW
5,2024-04-20,556.92,Nate,Hyland,Australia,Australia,Contoso Optical USB Mouse M45 Black,Computers,Computers Accessories,LOW
6,2024-04-20,399.44,Nate,Hyland,Australia,Australia,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,LOW
7,2024-04-20,63.30,Ruth,Steele,United States,North America,SV DVD 55DVD Storage Binder M56 Silver,"Music, Movies and Audio Books",Movie DVD,LOW
8,2024-04-20,8.34,Juliane,Naumann,Germany,Europe,SV Hand Games women M40 Yellow,Games and Toys,Boxed Games,LOW
9,2024-04-20,12.00,Juliane,Naumann,Germany,Europe,Contoso DVD 58 DVD Storage Binder M55 Black,"Music, Movies and Audio Books",Movie DVD,LOW