In [12]:
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [13]:
%%sql
SELECT *
FROM
sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [14]:
%%sql

SELECT *
FROM product
LIMIT 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3

In [15]:
# here we will run advanced statistical functions (Min, Max, Average and Median)
%%sql

SELECT
  MIN(netprice) AS min_netprice,
  MAX(netprice) AS max_netprice,
  AVG(netprice) AS AVG_netprice
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   min_netprice  max_netprice  avg_netprice
0          0.82       6247.50        324.30

In [16]:
# now grouping by categories and calculating ➡️ AVERAGE

%%sql

SELECT
  p.categoryname AS category_name,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS avg_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS avg_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
category_name
ORDER BY
category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  avg_2022  avg_2023
0                          Audio    392.30    425.38
1        Cameras and camcorders    1210.02   1210.96
2                    Cell phones    722.20    623.28
3                      Computers   1565.62   1292.39
4                 Games and Toys     81.29     80.83
5                Home Appliances   1755.36   1886.55
6  Music, Movies and Audio Books    386.61    334.58
7                   TV and Video   1535.61   1687.90

In [17]:
# now grouping by categories and calculating ➡️ MINIMUM

%%sql

SELECT
  p.categoryname AS category_name,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS min_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS min_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
category_name
ORDER BY
category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  min_2022  min_2023
0                          Audio      9.31     10.85
1        Cameras and camcorders       6.74      5.98
2                    Cell phones      2.53      2.28
3                      Computers      0.83      0.75
4                 Games and Toys      2.83      3.49
5                Home Appliances      4.04      4.54
6  Music, Movies and Audio Books      7.29      6.91
7                   TV and Video     41.30     42.30

In [21]:
# now grouping by categories and calculating ➡️ MAXIMUM

%%sql

SELECT
  p.categoryname AS category_name,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS max_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS max_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
category_name
ORDER BY
category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  max_2022  max_2023
0                          Audio   3473.36   2730.87
1        Cameras and camcorders   15008.39  13572.00
2                    Cell phones   7692.37   8912.22
3                      Computers  38082.66  27611.60
4                 Games and Toys   5202.01   3357.30
5                Home Appliances  31654.55  32915.59
6  Music, Movies and Audio Books   5415.19   3804.91
7                   TV and Video  30259.41  27503.12

In [20]:
# we can also group them all for better visibility
%%sql

SELECT
  p.categoryname AS category_name,

  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS avg_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS avg_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS min_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS min_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS max_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) AS max_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
category_name
ORDER BY
category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category_name,avg_2022,avg_2023,min_2022,min_2023,max_2022,max_2023
0,Audio,392.30,425.38,9.31,10.85,3473.36,2730.87
1,Cameras and camcorders,1210.02,1210.96,6.74,5.98,15008.39,13572.00
2,Cell phones,722.20,623.28,2.53,2.28,7692.37,8912.22
3,Computers,1565.62,1292.39,0.83,0.75,38082.66,27611.60
4,Games and Toys,81.29,80.83,2.83,3.49,5202.01,3357.30
5,Home Appliances,1755.36,1886.55,4.04,4.54,31654.55,32915.59
6,"Music, Movies and Audio Books",386.61,334.58,7.29,6.91,5415.19,3804.91
7,TV and Video,1535.61,1687.90,41.30,42.30,30259.41,27503.12

In [24]:
## For better calculations we use MEDIAN so that we can avoid outliers, in SQL Median is calculated by PERCENTILE_CONT(0.5)

%%sql

SELECT
  p.categoryname AS category_name,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY(s.quantity*s.netprice*s.exchangerate)) AS Median
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
category_name
ORDER BY
category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  median
0                          Audio  219.59
1        Cameras and camcorders   730.74
2                    Cell phones  459.88
3                      Computers  982.44
4                 Games and Toys   34.10
5                Home Appliances  696.08
6  Music, Movies and Audio Books  152.80
7                   TV and Video  682.83

In [27]:
# adding timeframe for 2022 and 2023

%%sql

SELECT
  p.categoryname AS category_name,

  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END)) AS Median_2022,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END)) AS Median_2023

FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
category_name
ORDER BY
category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  median_2022  median_2023
0                          Audio       257.21       266.59
1        Cameras and camcorders        651.46       672.60
2                    Cell phones       418.60       375.88
3                      Computers       809.70       657.18
4                 Games and Toys        33.78        32.62
5                Home Appliances       791.00       825.25
6  Music, Movies and Audio Books       186.58       159.63
7                   TV and Video       730.46       790.79