In [11]:
# now we will look into some othe methods to group in the categories

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT *
FROM sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [4]:
# using the sales tables we can classify orders according to quantities and amount

%%sql

SELECT
  orderdate,
  quantity,
  netprice,
CASE
  WHEN quantity >=5 AND netprice >= 80 THEN 'High Value'
  ELSE 'Standard Value'
  END AS order_type
FROM sales
ORDER BY orderdate
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice      order_type
0  2015-01-01         1    659.78  Standard Value
1  2015-01-01         2     54.38  Standard Value
2  2015-01-01         4    286.69  Standard Value
3  2015-01-01         7    135.75      High Value
4  2015-01-01         3    434.30  Standard Value
5  2015-01-01         1     58.73  Standard Value
6  2015-01-01         3     74.99  Standard Value
7  2015-01-01         2    113.57  Standard Value
8  2015-01-01         1    499.45  Standard Value
9  2015-01-01         1     98.97  Standard Value

In [5]:
# to divide the total revenue base on high and low we have to get the median of total data for 2022-2023

%%sql

SELECT
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY(quantity*netprice*exchangerate)) AS median
FROM
sales
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [6]:
# now lets apply the function for to categorize

%%sql

SELECT
  p.categoryname AS category_name,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) < 398
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS low_net_revenue,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) >= 398
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS high_net_revenue

FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
GROUP BY
  category_name
ORDER BY
  category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  low_net_revenue  high_net_revenue
0                          Audio        402588.95        1053039.44
1        Cameras and camcorders         237874.00        4128204.85
2                    Cell phones       1544148.92       12577663.79
3                      Computers       1215130.73       28297949.97
4                 Games and Toys        438083.00         148419.27
5                Home Appliances        396058.42       12136381.13
6  Music, Movies and Audio Books       1260767.25        3909298.16
7                   TV and Video        436613.64        9790901.19

In [7]:
# getting for both years

%%sql

WITH median_value AS (
  SELECT
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY(quantity*netprice*exchangerate)) AS median
FROM
sales
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category_name,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) < mv.median
  AND orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS low_revenue_2022,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) >= mv.median
  AND orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS high_revenue_2022,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) < mv.median
  AND orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS low_revenue_2023,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) >= mv.median
  AND orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS high_revenue_2023


FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey,
  median_value mv
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
GROUP BY
  category_name
ORDER BY
  category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category_name,low_revenue_2022,high_revenue_2022,low_revenue_2023,high_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [8]:
# comparing low net revenue for year 2022 and 2023

%%sql

WITH median_value AS (
  SELECT
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY(quantity*netprice*exchangerate)) AS median
FROM
sales
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category_name,

  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) < mv.median
  AND orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS low_revenue_2022,


  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) < mv.median
  AND orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS low_revenue_2023


FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey,
  median_value mv
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
GROUP BY
  category_name
ORDER BY
  category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  low_revenue_2022  low_revenue_2023
0                          Audio         222337.83         180251.13
1        Cameras and camcorders          133004.54         104869.46
2                    Cell phones         814449.53         729699.39
3                      Computers         624340.42         590790.31
4                 Games and Toys         231979.63         206103.36
5                Home Appliances         219797.07         176261.35
6  Music, Movies and Audio Books         685808.49         574958.76
7                   TV and Video         272338.29         164275.35

In [9]:
# comparing high net revenue for year 2022 and 2023

%%sql

WITH median_value AS (
  SELECT
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY(quantity*netprice*exchangerate)) AS median
FROM
sales
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category_name,



  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) >= mv.median
  AND orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS high_revenue_2022,


  SUM(CASE WHEN (s.quantity*s.netprice*s.exchangerate) >= mv.median
  AND orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity*s.netprice*s.exchangerate) END) AS high_revenue_2023


FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey,
  median_value mv
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
GROUP BY
  category_name
ORDER BY
  category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  high_revenue_2022  high_revenue_2023
0                          Audio          544600.39          508439.06
1        Cameras and camcorders          2249528.02         1878676.83
2                    Cell phones         7305215.55         5272448.24
3                      Computers        17237873.07        11060076.90
4                 Games and Toys           84147.67           64271.60
5                Home Appliances         6392649.61         5743731.52
6  Music, Movies and Audio Books         2303488.80         1605809.37
7                   TV and Video         5542998.32         4247902.87

In [10]:
# in this section we can also calculate categorywise median as well
%%sql
SELECT
  p.categoryname AS category_name,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity*s.netprice*s.exchangerate)) AS median
FROM sales s
LEFT JOIN product p ON p.productkey = s.productkey
  WHERE s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
GROUP BY category_name

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                   category_name  median
0                          Audio  262.25
1        Cameras and camcorders   659.87
2                    Cell phones  399.18
3                      Computers  738.00
4                 Games and Toys   33.12
5                Home Appliances  806.53
6  Music, Movies and Audio Books  171.31
7                   TV and Video  758.32

In [20]:
# adding that same expression to table
%%sql


WITH category_median AS (
  SELECT
    p.categoryname,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM sales s
  LEFT JOIN product p ON p.productkey = s.productkey
  WHERE s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
  GROUP BY p.categoryname
)

SELECT
  p.categoryname AS category_name,
  AVG(cm.median) AS median,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < cm.median
    AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
    THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS low_revenue_2022,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= cm.median
    AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
    THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS high_revenue_2022,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < cm.median
    AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
    THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS low_revenue_2023,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= cm.median
    AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
    THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS high_revenue_2023

FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
LEFT JOIN category_median cm ON p.categoryname = cm.categoryname
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category_name,median,low_revenue_2022,high_revenue_2022,low_revenue_2023,high_revenue_2023
0,Audio,262.25,126838.74,640099.47,104149.73,584540.45
1,Cameras and camcorders,659.87,293581.87,2088950.69,233563.52,1749982.77
2,Cell phones,399.18,823209.90,7296455.17,738857.59,5263290.05
3,Computers,738.00,1786099.84,16076113.65,1477250.73,10173616.48
4,Games and Toys,33.12,29987.45,286139.85,26589.38,243785.58
5,Home Appliances,806.53,678256.92,5934189.76,553520.90,5366471.98
6,"Music, Movies and Audio Books",171.31,244819.89,2744477.39,218088.71,1962679.42
7,TV and Video,758.32,683842.56,5131494.05,460417.94,3951760.28

In [21]:

%%sql

SELECT *

FROM sales
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00

In [29]:
# now lets use multiple WHEN arguments

%%sql

SELECT
  orderdate,
  quantity,
  netprice,
CASE
  WHEN quantity >= 2 AND netprice > 150 THEN 'Multiple High Value Items'
  WHEN netprice > 150 THEN 'Single High Value Items'
  WHEN netprice < 150 THEN ' Multiple Standard Value Items'
  ELSE 'Single standard value items'
  END AS order_type
FROM sales
ORDER BY orderdate
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                      order_type
0  2015-01-01         1    659.78         Single High Value Items
1  2015-01-01         2     54.38   Multiple Standard Value Items
2  2015-01-01         4    286.69       Multiple High Value Items
3  2015-01-01         7    135.75   Multiple Standard Value Items
4  2015-01-01         3    434.30       Multiple High Value Items
5  2015-01-01         1     58.73   Multiple Standard Value Items
6  2015-01-01         3     74.99   Multiple Standard Value Items
7  2015-01-01         2    113.57   Multiple Standard Value Items
8  2015-01-01         1    499.45         Single High Value Items
9  2015-01-01         1     98.97   Multiple Standard Value Items

In [32]:
# grouping base on percentiles
# 0-25 - Low, 25-75 - Mediam, 75+ - High

%%sql
  SELECT
  PERCENTILE_CONT(0.25) WITHIN GROUP(  ORDER BY(netprice*exchangerate*quantity)) AS Q1,
  PERCENTILE_CONT(0.75) WITHIN GROUP(  ORDER BY(netprice*exchangerate*quantity)) AS Q3
  FROM sales
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

      q1      q3
0 111.07 1062.12

In [48]:
# applying the same for the condition on the category to categorize

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                    category_name revenue_type  total_revenue
0                           Audio       1-High     1213265.71
1                           Audio     2-Medium     3832415.38
2                           Audio        3-Low      267217.01
3         Cameras and camcorders        1-High    15050781.63
4         Cameras and camcorders      2-Medium     3388546.10
5         Cameras and camcorders         3-Low       81032.92
6                     Cell phones       1-High    21874993.15
7                     Cell phones     2-Medium    10338963.22
8                     Cell phones        3-Low      410309.35
9                       Computers       1-High    79607760.89
10                      Computers     2-Medium    10808054.11
11                      Computers        3-Low      203207.06
12                 Games and Toys       1-High      133749.09
13                 Games and Toys     2-Medium     1001381.91
14                 Games and Toys        3-Low      533443.13
15                Home Appliances       1-High    22383475.30
16                Home Appliances     2-Medium     4118724.64
17                Home Appliances        3-Low      105045.60
18  Music, Movies and Audio Books       1-High     3844996.29
19  Music, Movies and Audio Books     2-Medium     6100817.99
20  Music, Movies and Audio Books        3-Low      642496.71
21                   TV and Video       1-High    16632856.33
22                   TV and Video     2-Medium     3766783.30
23                   TV and Video        3-Low       67221.76

In [64]:
# to be more precise we can also add category wise percentile as we did earlier

%%sql

WITH category_perc AS (
  SELECT
  p.categoryname,
  PERCENTILE_CONT(0.25) WITHIN GROUP(  ORDER BY(s.netprice*s.exchangerate*s.quantity)) AS Q1,
  PERCENTILE_CONT(0.75) WITHIN GROUP(  ORDER BY(s.netprice*s.exchangerate*s.quantity)) AS Q3
 FROM sales s
  LEFT JOIN product p ON p.productkey = s.productkey
  WHERE s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
  GROUP BY p.categoryname)

SELECT
  p.categoryname AS category_name,
  pc.Q1 AS q1_threshold,
  pc.Q3 AS q3_threshold,
CASE
  WHEN (s.netprice*s.exchangerate*s.quantity) > pc.Q3 THEN '1-High'
  WHEN (s.netprice*s.exchangerate*s.quantity) < pc.Q1 THEN '3-Low'
  ELSE '2-Medium' END AS revenue_type,
  SUM(s.netprice*s.exchangerate*s.quantity) AS total_revenue
FROM sales s
  LEFT JOIN product p ON s.productkey = p.productkey
  LEFT JOIN category_perc pc ON p.categoryname = pc.categoryname
GROUP BY
  p.categoryname,
pc.Q1,
pc.Q3,
  revenue_type
ORDER BY
  category_name,
  revenue_type;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,category_name,q1_threshold,q3_threshold,revenue_type,total_revenue
0,Audio,121.81,526.37,1-High,2941129.03
1,Audio,121.81,526.37,2-Medium,2050895.97
2,Audio,121.81,526.37,3-Low,320873.10
3,Cameras and camcorders,276.02,1536.86,1-High,13138022.15
4,Cameras and camcorders,276.02,1536.86,2-Medium,4948997.27
5,Cameras and camcorders,276.02,1536.86,3-Low,433341.24
6,Cell phones,116.96,949.41,1-High,23183055.19
7,Cell phones,116.96,949.41,2-Medium,9004041.96
8,Cell phones,116.96,949.41,3-Low,437168.56
9,Computers,294.00,1722.22,1-High,70324428.09
10,Computers,294.00,1722.22,2-Medium,19034411.27
11,Computers,294.00,1722.22,3-Low,1260182.69
12,Games and Toys,14.23,86.00,1-High,1240326.03
13,Games and Toys,14.23,86.00,2-Medium,386153.11
14,Games and Toys,14.23,86.00,3-Low,42095.00
15,Home Appliances,329.97,2032.00,1-High,18238001.41
16,Home Appliances,329.97,2032.00,2-Medium,7566060.92
17,Home Appliances,329.97,2032.00,3-Low,803183.21
18,"Music, Movies and Audio Books",52.92,463.92,1-High,7239457.83
19,"Music, Movies and Audio Books",52.92,463.92,2-Medium,3112086.98
20,"Music, Movies and Audio Books",52.92,463.92,3-Low,236766.18
21,TV and Video,329.47,1727.27,1-High,14256042.71
22,TV and Video,329.47,1727.27,2-Medium,5478558.41
23,TV and Video,329.47,1727.27,3-Low,732260.26