In [9]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [10]:
# using interval function
%%sql

SELECT INTERVAL '1 year'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  interval
0 365 days

In [11]:
# like previous practice we can use INTERVAL function to get past 5 years timeframe

%%sql

SELECT
  orderdate
FROM sales
  WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

111110 rows affected.

         orderdate
0       2021-03-22
1       2021-03-22
2       2021-03-22
3       2021-03-22
4       2021-03-22
...            ...
111105  2024-04-20
111106  2024-04-20
111107  2024-04-20
111108  2024-04-20
111109  2024-04-20

[111110 rows x 1 columns]

In [13]:
# we can filter data with less code
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.netprice*s.exchangerate*s.quantity) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE orderdate >= CURRENT_DATE - INTERVAL '6 years'
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10558 rows affected.

        orderdate                   categoryname  net_revenue
0      2020-03-22                          Audio       186.30
1      2020-03-23                          Audio       698.14
2      2020-03-23                    Cell phones      2191.68
3      2020-03-23                      Computers     19265.95
4      2020-03-23                 Games and Toys       420.74
...           ...                            ...          ...
10553  2024-04-20                      Computers     58353.68
10554  2024-04-20                 Games and Toys      1744.30
10555  2024-04-20                Home Appliances      1562.04
10556  2024-04-20  Music, Movies and Audio Books      4949.43
10557  2024-04-20                   TV and Video      9841.91

[10558 rows x 3 columns]

In [26]:
# using the AGE function

%%sql

SELECT
AGE('2020-01-22', '2020-01-12')

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

      age
0 10 days

In [25]:
# extraction
%%sql
  SELECT EXTRACT (DAY FROM AGE('2020-03-22', '2020-01-12'))

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  extract
0      10

In [30]:
# using AGE function we can get processing time
  %%sql

  SELECT
    orderdate,
    deliverydate,
    AGE(deliverydate, orderdate) AS processing_time
  FROM sales
  ORDER BY RANDOM()
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate deliverydate processing_time
0  2023-10-23   2023-10-26          3 days
1  2015-05-13   2015-05-13          0 days
2  2023-01-09   2023-01-14          5 days
3  2018-06-25   2018-06-25          0 days
4  2019-06-26   2019-06-26          0 days
5  2023-07-01   2023-07-03          2 days
6  2022-12-20   2022-12-22          2 days
7  2022-05-12   2022-05-15          3 days
8  2019-07-01   2019-07-01          0 days
9  2021-06-11   2021-06-11          0 days

In [45]:
# calculating avg processing time for distinct years

%%sql

SELECT
  EXTRACT (YEAR FROM orderdate) AS order_year,
  AVG(EXTRACT (DAYS FROM AGE(deliverydate, orderdate))) AS processing_time
FROM sales
GROUP BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_year         processing_time
0       2024  1.66696278748396012240
1       2016      1.0828877005347594
2       2021      1.3570381602223907
3       2018  0.86241686648871193956
4       2015      1.0982768691588785
5       2020  0.92988373125055471732
6       2017  0.83310293982121463460
7       2023      1.7526721219713730
8       2022      1.6233962099189089
9       2019  0.81467910282034199423

In [46]:
# fixing the formatting

%%sql

SELECT
  EXTRACT (YEAR FROM orderdate) AS order_year,
  ROUND(AVG(EXTRACT (DAYS FROM AGE(deliverydate, orderdate))),2) AS processing_time,
  CAST(SUM(quantity*netprice*exchangerate) AS INTEGER) AS net_revenue
FROM sales
WHERE orderdate >= CURRENT_DATE - INTERVAL '8 years'
GROUP BY
  order_year
ORDER BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

7 rows affected.

  order_year processing_time  net_revenue
0       2018            0.89     19939014
1       2019            0.81     31818096
2       2020            0.93     11218436
3       2021            1.36     21357977
4       2022            1.62     44864557
5       2023            1.75     33108566
6       2024            1.67      8396527