In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
# using window function


%%sql

SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity*netprice*exchangerate) AS net_revenue,



  AVG(quantity*netprice*exchangerate)  OVER() AS avg_net_revenue_all_orders, -- window function
  AVG(quantity*netprice*exchangerate)  OVER(PARTITION BY customerkey) AS avg_net_revenue_this_customer -- window function

FROM sales
ORDER BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_this_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,1305016,0,525.31,1032.69,836.74
2,180,3162018,0,71.36,1032.69,836.74
3,180,3162018,1,1913.55,1032.69,836.74
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,2495044,0,1265.56,1032.69,517.32
7,387,3242015,2,180.35,1032.69,517.32
8,387,3242015,3,446.44,1032.69,517.32
9,387,3242015,0,30.51,1032.69,517.32

In [3]:


%%sql

SELECT

  customerkey AS customer,
  orderdate AS order_date,
  (quantity*netprice*exchangerate) AS net_revenue,

  ROW_NUMBER() OVER(PARTITION BY customerkey ORDER BY quantity*netprice*exchangerate DESC) AS order_rank,
  (quantity*netprice*exchangerate) / sum(quantity*netprice*exchangerate) OVER(PARTITION BY customerkey)*100 AS pct_customer_revenue,
  SUM(quantity*netprice*exchangerate) OVER(PARTITION BY customerkey) AS customer_net_revenue,
  SUM(quantity*netprice*exchangerate) OVER(PARTITION BY customerkey ORDER BY orderdate) AS customer_running_total

FROM sales
LIMIT 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,customer,order_date,net_revenue,order_rank,pct_customer_revenue,customer_net_revenue,customer_running_total
0,15,2021-03-08,2217.41,1,100.00,2217.41,2217.41
1,180,2023-08-28,1913.55,1,76.23,2510.22,2510.22
2,180,2018-07-28,525.31,2,20.93,2510.22,525.31
3,180,2023-08-28,71.36,3,2.84,2510.22,2510.22
4,185,2019-06-01,1395.52,1,100.00,1395.52,1395.52

In [6]:
# furthur operations
%%sql

SELECT
  orderdate,
  orderkey,
  linenumber,
  (quantity*netprice*exchangerate) AS net_revenue
FROM
  sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  orderkey  linenumber  net_revenue
0  2015-01-01      1000           0        63.49
1  2015-01-01      1000           1       423.28
2  2015-01-01      1001           0       108.75
3  2015-01-01      1002           0      1146.75
4  2015-01-01      1002           1       950.25
5  2015-01-01      1002           2      1302.91
6  2015-01-01      1002           3        58.73
7  2015-01-01      1003           0       224.98
8  2015-01-01      1004           0       263.11
9  2015-01-01      1004           1       578.52

In [10]:
# furthur operations
%%sql

SELECT
  orderdate,
  orderkey*10 + linenumber AS order_line_item,
  (quantity*netprice*exchangerate) AS net_revenue,
  SUM(quantity*netprice*exchangerate) OVER(PARTITION BY orderdate) AS daily_revenue,
  100*(quantity*netprice*exchangerate) / SUM(quantity*netprice*exchangerate) OVER(PARTITION BY orderdate) AS pct_daily_revenue
FROM
  sales
ORDER BY
  orderdate,
  pct_daily_revenue DESC
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  order_line_item  net_revenue  daily_revenue  pct_daily_revenue
0  2015-01-01            10043      2395.10       11640.80              20.58
1  2015-01-01            10061      1552.32       11640.80              13.34
2  2015-01-01            10022      1302.91       11640.80              11.19
3  2015-01-01            10020      1146.75       11640.80               9.85
4  2015-01-01            10050       975.16       11640.80               8.38
5  2015-01-01            10021       950.25       11640.80               8.16
6  2015-01-01            10041       578.52       11640.80               4.97
7  2015-01-01            10081       574.05       11640.80               4.93
8  2015-01-01            10001       423.28       11640.80               3.64
9  2015-01-01            10040       263.11       11640.80               2.26

In [13]:
# extracting the cohort year using window function

%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey cohort_year
0           15        2021
1          180        2018
2          180        2018
3          180        2018
4          185        2019
5          243        2016
6          387        2018
7          387        2018
8          387        2018
9          387        2018

In [20]:
# using cte adding a column of cohort year

%%sql

WITH yearly_cohort AS(
    SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM sales
)

SELECT *
FROM sales s
LEFT JOIN yearly_cohort y ON y.customerkey = s.customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate,customerkey,cohort_year
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64,947009,2015
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64,947009,2015
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00,1772036,2015
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00,1518349,2015
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00,1518349,2015
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00,1518349,2015
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00,1518349,2015
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00,1317097,2015
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16,254117,2015
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16,254117,2015

In [21]:
# creating the table for cohort year and purchase year

%%sql

WITH yearly_cohort AS(
    SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM sales
)

SELECT
  y.cohort_year,
  EXTRACT(YEAR FROM s.orderdate) AS purchase_year,
  SUM(s.quantity*s.netprice*s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN yearly_cohort y ON y.customerkey = s.customerkey
GROUP BY
  y.cohort_year,
  purchase_year
ORDER BY
  y.cohort_year,
  purchase_year
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year purchase_year  net_revenue
0        2015          2015   7370979.48
1        2015          2016    392623.48
2        2015          2017    479841.31
3        2015          2018   1069850.87
4        2015          2019   1235991.48
5        2015          2020    386489.60
6        2015          2021    872845.99
7        2015          2022   1569787.72
8        2015          2023   1157633.91
9        2015          2024    356186.62